name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
- repo: self
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - deploy/automation/docker-hub/ci/*
pr: none
variables:
  LogicApp.Name: 'k8s-event-bridge-automation-github-ci-docker-hub'
  GitHub.Repo.Owner: 'tomkerkhove'
  GitHub.Repo.Name: 'k8s-event-bridge'
  GitHub.Bot.Name: 'docker-hub-bot'
pool:
  vmImage: vs2017-win2016
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in tooling'
  inputs:
    rootDirectory: 'deploy/automation/docker-hub/ci/'
    targetFiles: azuredeploy.parameters.json
    verbosity: detailed
    actionOnMissing: fail

- task: AzureResourceGroupDeployment@2
  displayName: 'Deploy CI bot for Docker Hub updates'
  inputs:
    azureSubscription: 'Visual Studio Enterprise (0f9d7fea-99e8-4768-8672-06a28514f77e)'
    resourceGroupName: k8s-event-bridge
    location: 'West Europe'
    csmFile: 'deploy/automation/docker-hub/ci/azuredeploy.json'
    csmParametersFile: 'deploy/automation/docker-hub/ci/azuredeploy.parameters.json'