apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-event-grid-bridge.fullname" . }}
  labels:
    {{- include "k8s-event-grid-bridge.labels" . | nindent 4 }}
data:
  AzureWebJobsStorage: {{ .Values.azure.storage.connectionString | b64enc | quote }}
  EventGridAuthenticationKey: {{ .Values.azure.eventGrid.key | b64enc | quote }}