name: Event type request ⚡
description: Suggest a new event type that would be an added value
labels: "event-type,feature-request"
assignees: tomkerkhove
body:
- type: input
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  attributes:
    label: Scenario
    description: "What scenario will this new event type support?"
    placeholder: "A clear and concise description of the scenario where this type would be used."
- type: input
  attributes:
    label: Proposed Event Type
    description: "What event type would you propose?"
    placeholder: "A proposal for the event type, for example `Kubernetes.ClusterAutoscaler.Scale.Out`."
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Event Payload
    description: What event payload would you propose?
    placeholder: "A proposal for the event payload that you would like to have."
    value: |
      ```json
      {
        "key": "value"
      }
      ```
  validations:
    required: false
- type: textarea
  attributes:
    label: Raw Kubernetes Event
    description: What is the raw Kubernetes event that we should convert for this event?
    placeholder: "A raw Kubernetes event payload that is the source."
    value: |
      ```json
      {
        "key": "value"
      }
      ```
  validations:
    required: false
- type: dropdown
  attributes:
    label: Source Component
    description: What component is emitting the original raw event?
    options:
    - Kubernetes Control Plane
    - Cluster Autoscaler
    - Other
  validations:
    required: false
