blank_issues_enabled: true
contact_links:
  - name: Ask a question 💬
    url: https://github.com/tomkerkhove/k8s-event-grid-bridge/discussions/new
    about: Ask a question or request support for using Kubernetes Event Grid Bridge.
  - name: Sponsor 💘
    url: https://github.com/sponsors/tomkerkhove
    about: Sponsor Tom to keep on maintaining Kubernetes Event Grid Bridge.
