data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
  name: container-name
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-name
  namespace: default
  labels:
    app: container-name
spec:
  selector:
    matchLabels:
      app: container-name
  template:
    metadata:
      labels:
        app: container-name
    spec:
      containers:
      - name: container-name
        image: tomkerkhove/k8s-event-bridge:dev
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: kubernetes-event-bridge
        envFrom:
        - secretRef:
            name: container-name
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: container-name
  namespace: default
  labels:
    deploymentName: container-name
spec:
  scaleTargetRef:
    deploymentName: container-name
  triggers:
  - type: daprbindingtrigger
    metadata:
      type: daprBindingTrigger
      bindingName: k8s-event-bridge-bindings-kubernetes
      name: triggerData
---

