name: CI (Runtime)
on:
  pull_request:
    paths:
    - 'src/**'

env:
  IMAGE_NAME: ghcr.io/tomkerkhove/k8s-event-grid-bridge
  IMAGE_TAG: experimental
  
jobs:
  solution:
    name: Solution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: dotnet build ./src/Kubernetes.EventGrid.Bridge.sln
    - name: Run Unit Tests
      run: dotnet test ./src/Kubernetes.EventGrid.Tests.Unit/Kubernetes.EventGrid.Tests.Unit.csproj --filter Category=Unit
  runtime:
    name: Runtime (Docker)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src/ --file ./src/Kubernetes.EventGrid.Bridge.Host/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
