name: Test Action
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.2.0-rc.1'
  release:
    types: [published]
env:
  IMAGE_NAME: ghcr.io/tomkerkhove/k8s-event-grid-bridge
  IMAGE_TAG: "${{ github.event.release.tag_name }}"
  NUGET_PACKAGE_NAME: Kubernetes.EventGrid.Bridge.Contracts.$NUGET_VERSION.nupkg
  NUGET_PACKAGE_PATH: ./src/Kubernetes.EventGrid.Bridge.Contracts/bin/Release/$NUGET_PACKAGE_NAME
jobs:
  verify:
    name: Verify App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: dotnet test ./src/Kubernetes.EventGrid.Tests.Unit/Kubernetes.EventGrid.Tests.Unit.csproj --filter Category=Unit
  push_nuget_to_ghpr:
    name: Push NuGet package to NuGet.org
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
    - uses: actions/checkout@v2
    - name: Set version suffix for release trigger
      uses: allenevans/set-env@v2.0.0
      if: ${{ github.event_name == 'release' }}
      with:
        NUGET_VERSION: ${{ github.event.release.tag_name }}
    - name: Set version suffix for workflow dispatch
      uses: allenevans/set-env@v2.0.0
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        NUGET_VERSION: ${{ github.event.inputs.version }}
    - name: Build Solution
      run: dotnet build ./src/Kubernetes.EventGrid.Bridge.sln --configuration Release -p:Version=${{ env.NUGET_VERSION }}
    - name: Output Path
      run: echo ${{ env.NUGET_PACKAGE_PATH }}
    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NUGET_PACKAGE_NAME }}
        path: ${{ env.NUGET_PACKAGE_PATH }}
